## Pandas
### BIOINF 575

_____


### NumPy - Numeric python <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png" alt="NumPy logo" width = "100">

____
#### A list contains refences to each of the values.
#### An array refers to a block of memory containg all values one after the other.
- <b>that is why we need to know the size of the array and the array size cannot change <br>


<img src = "https://www.python-course.eu/images/list_structure.png" width = 350 /> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src = "https://www.python-course.eu/images/array_structure.png" width = 350 />
____

#### Arrays of different dimensions (`shape` gives the number of elements on each dimension):
<img src="https://raw.githubusercontent.com/elegant-scipy/elegant-scipy/master/figures/NumPy_ndarrays_v2.svg" alt="data structures" width="600">  

https://github.com/elegant-scipy/elegant-scipy
_____

#### <b>NumPy basics</b>

Arrays are designed to:
* <b>handle vectorized operations (lists cannot do that)</b>
    - if you apply a function it is performed on every item in the array, rather than on the whole array object
    - both arrays and lists have 0-based indexing
* <b>store multiple items of the same data type</b>
* <b>handle missing values </b>
    - missing numerical values are represented using the `np.nan` object (not a number)
    - the object `np.inf` represents infinite  
* <b>have an unchangeable size</b>
    - array size cannot be changed, should create a new array if you want to change the size
    - you know when you create the array how much space you need for it and that will not change  
* <b>have efficient memory usage</b>
    - an equivalent numpy array occupies much less space than a python list of lists

#### <b>Basic array attributes:</b>
* shape: array dimension
* size: Number of elements in array
* ndim: Number of array dimension (len(arr.shape))
* dtype: Data-type of the array

#### <b>Importing NumPy
The recommended convention to import numpy is to use the <b>np</b> alias:

In [60]:
import numpy as np

#### <b>Documentation and help
https://numpy.org/doc/

In [61]:
# np.lookfor('sum')

In [62]:
np.me*?

np.mean
np.median
np.memmap
np.meshgrid

In [63]:
# np.mean?

In [64]:
# help(np.mean)

_____

### Pandas
<img src = "https://upload.wikimedia.org/wikipedia/commons/e/ed/Pandas_logo.svg" width = 200/>

https://commons.wikimedia.org/wiki/File:Pandas_logo.svg

[Pandas](https://pandas.pydata.org/) is a high-performance library that makes familiar data structures, like `data.frame` from R, and appropriate data analysis tools available to Python users.

<img src = "https://media.geeksforgeeks.org/wp-content/uploads/finallpandas.png" width = 550/>

https://www.geeksforgeeks.org/python-pandas-dataframe/

#### How does pandas work?

Pandas is built off of [Numpy](http://www.numpy.org/), and therefore leverages Numpy's C-level speed for its data analysis.

* Numpy can only make data structures of a single type.
* Pandas can use many types. 
* Think of a table, where each column can be whatever type you want it to be, so long as every item in the column is that same type.

#### Why use pandas?

1. Data munging/wrangling: the cleaning and preprocessing of data
2. Loading data into memory from disparate data formats (SQL, CSV, TSV, JSON)

#### Importing

Pandas is built off of numpy, it is usefull to import numpy at the same time, but not necessary.

```python
import numpy as np
import pandas as pd


```

#### 1. `pd.Series`

**One-dimensional** labeled array (or vector)

```python
# Initialization Syntax
series = pd.Series(data, index, dtype) 
```

* **`data`** : what is going inside the Series (array-like, dict, or scalar value)
* **`index`**: row identifiers (doesn't have to be unique--think foreign key. Defaults to row number)
* **`dytpe`**: numpy/python based data types

Attributes 

['T',
 'array',
 'at',
 'axes',
 'base',
 'data',
 'dtype',
 'dtypes',
 'empty',
 'flags',
 'ftype',
 'ftypes',
 'hasnans',
 'iat',
 'iloc',
 'imag',
 'index',
 'is_monotonic',
 'is_monotonic_decreasing',
 'is_monotonic_increasing',
 'is_unique',
 'itemsize',
 'ix',
 'loc',
 'name',
 'nbytes',
 'ndim',
 'plot',
 'real',
 'shape',
 'size',
 'strides',
 'timetuple',
 'values']
 
 
 Methods
 
 ['abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'argmax',
 'argmin',
 'argsort',
 'asfreq',
 'asof',
 'astype',
 'at_time',
 'autocorr',
 'between',
 'between_time',
 'bfill',
 'bool',
 'clip',
 'combine',
 'combine_first',
 'convert_dtypes',
 'copy',
 'corr',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'div',
 'divide',
 'divmod',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'duplicated',
 'eq',
 'equals',
 'ewm',
 'expanding',
 'explode',
 'factorize',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'floordiv',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'idxmax',
 'idxmin',
 'infer_objects',
 'interpolate',
 'isin',
 'isna',
 'isnull',
 'item',
 'items',
 'iteritems',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'lt',
 'mad',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'memory_usage',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pct_change',
 'pipe',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'radd',
 'rank',
 'ravel',
 'rdiv',
 'rdivmod',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'repeat',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'searchsorted',
 'sem',
 'set_axis',
 'shift',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'std',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_frame',
 'to_hdf',
 'to_json',
 'to_latex',
 'to_list',
 'to_markdown',
 'to_numpy',
 'to_period',
 'to_pickle',
 'to_sql',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tshift',
 'tz_convert',
 'tz_localize',
 'unique',
 'unstack',
 'update',
 'value_counts',
 'var',
 'view',
 'where',
 'xs']

#### Create a Series from a Python list

In [65]:
import numpy as np
import pandas as pd

In [66]:

labels = ["EGFR","IL6","BRAF","ABL"]
values = [3,4,3,6]
gene_snp_no = pd.Series(data = values, index=labels)

In [67]:
# Get the data, name, labels, value counts for the series

#### Create a Series from a dictionary

In [68]:
gene_expr_map = {"EGFR":2.5, "IL6":10.2, "BRAF":6.7, "ABL":5.3}
# Create new series
gene_expr_vals = pd.Series(data = gene_expr_map)

In [69]:
## Which genes have an expression greater then 5.5?

In [70]:
## Which gene has the highest expression value?

## .idmax() - Return the index of the row with the max value

#### Random data
https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.random.html

In [71]:
# Create an array filled with random values 
# Results are from the “continuous uniform” distribution over the [0,1] interval.

# help(np.random.random)

In [72]:
# Generate the same random numbers every time
# Set seed

np.random.seed(42)

In [73]:
# Create an array filled with random values from the standard normal distribution
help(np.random.randn)

Help on built-in function randn:

randn(...) method of numpy.random.mtrand.RandomState instance
    randn(d0, d1, ..., dn)

    Return a sample (or samples) from the "standard normal" distribution.

    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `standard_normal`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.

    .. note::
        New code should use the
        `~numpy.random.Generator.standard_normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    If positive int_like arguments are provided, `randn` generates an array
    of shape ``(d0, d1, ..., dn)``, filled
    with random floats sampled from a univariate "normal" (Gaussian)
    distribution of mean 0 and variance 1. A single float randomly sampled
    from the distribution is returned if no argument is provided.

    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.

    Returns
    -------
    Z : ndarray or float
        A ``(d0, d1, ..., dn)``-shaped array of floating-point samples from
        the standard normal distribution, or a single such float if
        no parameters were supplied.

    See Also
    --------
    standard_normal : Similar, but takes a tuple as its argument.
    normal : Also accepts mu and sigma arguments.
    random.Generator.standard_normal: which should be used for new code.

    Notes
    -----
    For random samples from the normal distribution with mean ``mu`` and
    standard deviation ``sigma``, use::

        sigma * np.random.randn(...) + mu

    Examples
    --------
    >>> np.random.randn()
    2.1923875335537315  # random

    Two-by-four array of samples from the normal distribution with
    mean 3 and standard deviation 2.5:

    >>> 3 + 2.5 * np.random.randn(2, 4)
    array([[-4.49401501,  4.00950034, -1.81814867,  7.29718677],   # random
           [ 0.39924804,  4.68456316,  4.99394529,  4.84057254]])  # random

#### 2. `pd.DataFrame`

**Multi-dimensional** labeled data structure with columns of *potentially* different types

```python
# Initialization Syntax
df = pd.DataFrame(data, index, columns, dtype)
```

* **`data`** : what is going inside the DataFrame (numpy ndarray (structured or homogeneous), dict, or DataFrame)
* **`index`** : row identifiers (doesn't have to be unique--think foreign key. Defaults to row number)
* **`columns`** : column identifiers
* **`dtype`** : numpy/python based data types

Attributes

['T',
 'at',
 'axes',
 'columns',
 'dtypes',
 'empty',
 'ftypes',
 'iat',
 'iloc',
 'index',
 'ix',
 'loc',
 'ndim',
 'plot',
 'shape',
 'size',
 'style',
 'timetuple',
 'values']

In [74]:
np.random.seed(42)
expression_array = np.random.random(20).reshape(4,5) * 100
genes = ["HER2","PIK3CA", "BRAF", "IL6"]
samples = ["Sample1","Sample2", "Sample3", "Sample4", "Sample5"]
gene_expr = pd.DataFrame(data = expression_array, 
                         index = genes, 
                         columns = samples)

In [75]:
# .describe() -  generate descriptive statistics

In [76]:
# Explore DataFrame attributes and methods .T, .shape, .size., .index, .columns 
# Get individual columns .<column_name>
# '.' operator selected columns are just a pd.Series and can be '[]' sliced on further

In [77]:
###

In [78]:
gene_expr

          Sample1    Sample2    Sample3    Sample4    Sample5
HER2    37.454012  95.071431  73.199394  59.865848  15.601864
PIK3CA  15.599452   5.808361  86.617615  60.111501  70.807258
BRAF     2.058449  96.990985  83.244264  21.233911  18.182497
IL6     18.340451  30.424224  52.475643  43.194502  29.122914

In [79]:
# we can sort the data by column - get the samples ranked by HER2 expression

gene_expr.T.sort_values(by='HER2', ascending=False)

              HER2     PIK3CA       BRAF        IL6
Sample2  95.071431   5.808361  96.990985  30.424224
Sample3  73.199394  86.617615  83.244264  52.475643
Sample4  59.865848  60.111501  21.233911  43.194502
Sample1  37.454012  15.599452   2.058449  18.340451
Sample5  15.601864  70.807258  18.182497  29.122914

In [80]:
# We can aggregate data - get lowest gene value accross samples

gene_expr.aggregate(np.min, 1)

/var/folders/vf/xrx6p_p938q93dmkgn0clhkc0000gn/T/ipykernel_82813/1826335492.py:3: FutureWarning: The provided callable <function min at 0x1041ac5e0> is currently using DataFrame.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  gene_expr.aggregate(np.min, 1)

HER2      15.601864
PIK3CA     5.808361
BRAF       2.058449
IL6       18.340451
dtype: float64

In [81]:
######

In [82]:
gene_expr

          Sample1    Sample2    Sample3    Sample4    Sample5
HER2    37.454012  95.071431  73.199394  59.865848  15.601864
PIK3CA  15.599452   5.808361  86.617615  60.111501  70.807258
BRAF     2.058449  96.990985  83.244264  21.233911  18.182497
IL6     18.340451  30.424224  52.475643  43.194502  29.122914

#### Append, join, and concat methods are used to add new rows/columns

In [83]:
# Add a new sample with the values 54.11, 20.65, 30.52, 96.86

# help(pd.DataFrame.join)

#### <b> I/O in Pandas

One of the the most common reasons people use pandas is to bring data in without having to deal with file I/O, delimiters, and type conversion. Pandas deals with a lot of this.

#### CSV Files

#### Output

You can easily save your `DataFrames`

In [84]:
gene_expr.to_csv('dataframe_data.csv')

In [85]:
# help(gene_expr.to_csv)

In [86]:
gene_expr.to_csv('dataframe_data.csv', index = True)

#### Input

You can easily bring data from a file into a `DataFrames`

In [87]:
pd.read_csv('dataframe_data.csv', index_col = 0)

          Sample1    Sample2    Sample3    Sample4    Sample5
HER2    37.454012  95.071431  73.199394  59.865848  15.601864
PIK3CA  15.599452   5.808361  86.617615  60.111501  70.807258
BRAF     2.058449  96.990985  83.244264  21.233911  18.182497
IL6     18.340451  30.424224  52.475643  43.194502  29.122914

##### ------

##### Excel Files (.to_excel(), .read_excel())
##### TSV Files (.csv( , sep = "\t"), .read_csv( , sep = "\t"))
##### Clipboard (.to_clipboard(), .read_clipboard() )

#____________________

#### <b>Indexing/Exploring/Manipulating in Pandas

Standard `'[]'` indexing/slicing can be used, as well as `'.'` methods,

There are 2 pandas-specific methods for indexing:
1. `.loc` -> primarily label/name-based
2. `.iloc` -> primarily integer-based

In [90]:

df_iris = pd.read_csv('https://raw.githubusercontent.com/uiuc-cse/data-fa14/gh-pages/data/iris.csv')

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

Pandas allows you to do random sampling from the dataframe

In [ ]:
df_small = df_iris.sample(n=5)
df_small

In [ ]:
# or see the first 5 rows: .head()

df_iris.head()

In [ ]:
### 

df_iris

#### `'[]'` slicing on a `pd.DataFrame` gives us a slice of **rows**
Named rows can be selected by a range of the names

#### Selection <b>BY NAME</b>: the `.loc` method

```python
# .loc syntax
df.loc[row indexer, column indexer]
```

<b>A slice of specific items (based on label) - start and stop included</b>

In [ ]:
df_iris.head()

#### Boolean indexing - returns rows that meet the condition

#### Selection <b>BY POSITION</b>: the `.iloc` method

<b>A slice of specific items (based on position)</b>

In [ ]:
# we can use a list of indices

#### Quick Exploration of the data

In [ ]:
# help(df_iris.groupby)

In [ ]:
# get the mean of the four characteristics grouped by species

#### Plots - using the `.` (`dot`) notation
##### `.hist`, `.plot`, `.boxplot`
##### <b>`plot`</b> `.scatter`, `.line`, `.bar`, `.box`, ...

In [ ]:
# dir(df_iris)

In [ ]:
for elem in dir(df_iris):
    if "plot" in elem:
        print(elem)

In [ ]:
for elem in dir(df_iris.plot):
    if "_" not in elem:
        print(elem)

In [ ]:
# Series objects have the plot method as well

for elem in dir(df_iris.petal_length):
    if "plot" in elem:
        print(elem)

In [ ]:
for elem in dir(df_iris.petal_length.plot):
    if "_" not in elem:
        print(elem)

In [ ]:
## boxplot of the 4 characteristics 
## which one varies the most and the least betweeen species?

df_iris.boxplot()

In [ ]:
# bar plot of petal length mean per species

In [ ]:
## check the dataframe for nas

bool(sum(df_iris.isnull().any()))

#### <font color = "red"> Exercise <font/>

In [1]:
## boxplot of the mean of the 4 characteristics for the species setosa
df_iris[df_iris['species'] == 'setosa'].boxplot()

NameError: name 'df_iris' is not defined

In [ ]:
## histogram of the sepal length for the versicolor species

In [ ]:
## Replace all values for the species "virginica" where sepal_length >7.5 or <  5.5 with np.nan

In [ ]:
## check the dataframe for missing values .isna().any()

#### RESOURCES

https://www.python-course.eu/pandas.phphttps://www.python-course.eu/numpy.php    
https://scipy-lectures.org/packages/statistics/index.html?highlight=pandas  
https://www.geeksforgeeks.org/pandas-tutorial/

https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf

<img src="https://pandas.pydata.org/Pandas_Cheat_Sheet.pdf" width=1000/>